name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Stylelint
        run: npm run lint:css

      - name: Run Typecheck
        run: npm run typecheck

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Run Integration tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          build: npm run build
          start: npm run serve
        env:
          CYPRESS_SUPPORT: 'y'
